#+title: [[https://leetcode.com/contest/weekly-contest-354/][Weekly Contest 354]]
#+author: Mathura Tudu
#+date: <2023-08-05 Sat>
#+property: header-args:cpp :tangle ./sol.h :main no

[[https://leetcode.com/contest/weekly-contest-354/problems/sum-of-squares-of-special-elements/][2778. Sum of Squares of Special Elements]]

To solve this problem, simply do what is asked. Keep adding the sum of squares of all *special* elements. Number at ~i-th~ position is said to be special if ~n%i == 0~

#+begin_src cpp
  class Solution {
  public:
    int sumOfSquares(vector<int>& arr) {
      int n = (int) arr.size();
      int sum = 0;
      for (int i = 1; i <= n; i++) {
        if (n % i == 0) {
          sum += arr[i - 1] * arr[i - 1];
        } 
      }
      return sum;
    }
  };
#+end_src


[[https://leetcode.com/contest/weekly-contest-354/problems/maximum-beauty-of-an-array-after-applying-operation/][2779. Maximum Beauty of an Array After Applying Operation]]

Use ~line sweep algorithm~. Imagine horizontal lines with starting and an ending point derived from ~nums~. i.e ~i-th~ line have starting point = ~nums[i]-k~, ending point = ~nums[i]+k~. Use a boolean to identify the starting and ending point of a line. Sort these points based on the position. Now, find the point where maximum overlapping between lines is happening (Imagine a vertical line which cuts through most of the lines). This can be found by scanning the points in order and maintain a counter. If an endpoint is encountered, decrement the counter else increment it. The maximum value attained by counter during this process shows the maximum overlap of lines.

#+begin_src cpp
  class Solution {
  public:
    int maximumBeauty(vector<int>& nums, int k) {
      int n = (int) nums.size();
      vector <pair <int, bool> > p(2 * n);
      for (int i = 0; i < n; i++) {
        p[i] = make_pair(nums[i] - k, false);
        p[n + i] = make_pair(nums[i] + k, true);
      }
      sort(p.begin(), p.end(), [&](auto &a, auto &b) {
        if (a.first == b.first) {
          if (a.second == b.second) {
            return false;      // for equivalent point, return false
          } 
          return b.second;
        }
        return a.first < b.first;
      });

      int ans = 0;
      int cnt = 0;
      for (auto &pr: p) {
        if (pr.second) {
          cnt--;
        } else {
          cnt++;
        }
        ans = max(ans, cnt);
      }
      return ans;
    }
  };
#+end_src


[[https://leetcode.com/contest/weekly-contest-354/problems/minimum-index-of-a-valid-split/][2780. Minimum Index of a Valid Split]]

First find the dominant element of the array, ~nums~. By definition, there can only be one dominant element. The same element will be the dominant element in both arrays after split. So first get this dominant element by storing the frequency of array elements in ~map~. Now we can try to split the array at index ~i~ starting from index 0, 1, 2 ... and so on. While we are at index ~i~, calculate the frequency of dominant element in both left and right side of split. If this element dominants both left and right array, we've found the answer, return ~i~

#+begin_src cpp
  class Solution {
  public:
    int minimumIndex(vector<int>& nums) {
      int n = (int) nums.size();
      map <int, int> mp;
      for (int v : nums) {
        mp[v]++;
      }

      int cnt = 0;
      int ele = -1;
      for (auto pr : mp) {
        if (pr.second > cnt) {
          cnt = pr.second;
          ele = pr.first;
        }
      }

      int lcnt = 0;
      // ele is the dominant element
      for (int i = 0; i <= n - 2; i++) {
        if (nums[i] == ele) {
          lcnt++;
          cnt--;
        }

        // nums[0...i] contains lcnt dominant elements, right of split contains cnt dominant element
        if ((lcnt * 2 > (i + 1)) && (cnt * 2 > (n - i - 1))) {
          return i;
        }
      }
      return -1;
    }
  };
#+end_src


[[https://leetcode.com/contest/weekly-contest-354/problems/length-of-the-longest-valid-substring/][2781. Length of the Longest Valid Substring]]

Since the length of ~forbidden~ word is ~<= 10~, we can try to generate all substrings of length atmost ~10~ and check if they are forbidden. If a substring is forbidden that can't be part of answer. We'll generate substrings starting from index ~i~, so substrings generated at worst case will be of form ~word[i:j]~ where ~i <= j <= i+9~. If we find that ~word[i:j]~ forms a forbidden word we know for sure answer can't contain this substring, but substring ~word[i:j-1]~ can still be part of answer. So we update the answer. What if all substrings starting from ~i~ are not forbidden? To handle such cases we maintain index ~r~ to signify the region ~word[i:r]~ doesn't have any forbidden substrings. This ~r~ needs to be updated whenever a substring ~word[i-j]~ contains forbidden word. Iterate ~i~ from ~word.length-1~ till ~0~.

=word[i-j]= : substring of ~word~ from index ~i~ to ~j~ (inclusive). 

#+begin_src cpp
  class Solution {
  public:
    int longestValidSubstring(string word, vector<string>& forbidden) {
      set <string> st;
      int max_len = 0; // can be upto 10 in some cases
      for (string w : forbidden) {
        max_len = max(max_len, (int) w.length());
        st.insert(w);
      }

      auto isForbidden = [&](int from, int to) {
        string sub = word.substr(from, to - from + 1);
        auto it = st.find(sub);
        return it != st.end();
      };

      int len = (int) word.length();
      int i = len - 1;
      // maintain a index r, meaning range [i-r] doesn't contain any substrings which are forbidden.
      int r = len - 1;
      int ans = 0;
      while (i >= 0) {
        int j = i;
        int upto = min(i + max_len - 1, r);
        while (j <= upto && !isForbidden(i, j)) {
          j++;
        }

        // if there is invalid substr in [i-upto], then j <= upto
        if (j <= upto) {
          j--;
          ans = max(ans, j - i + 1);
          r = j;
        } else {
          ans = max(ans, r - i + 1);
        }
        i--;
      }

      return ans;
    }
  };
#+end_src

